name: mpv_dart
description: MPV player's JSON IPC binding for Dart (Flutter)
version: 0.0.1
homepage: https://github.com/KRTirtho/mpv_dart
repository: https://github.com/KRTirtho/mpv_dart

publish_to: https://pub.dev
environment:
  sdk: '>=2.14.4 <3.0.0'

dev_dependencies:
  lints: ^2.0.1
dependencies: 
  path: ^1.8.0
